### ISSUE TITLE
Passing in own API key 

### ISSUE THREAD

**Issue by robweir** [filutkie/streetview-embed#3]
Hi there, when attempting to embed a pano on this page: 

http://j4502-ss16.github.io/weir/maps/index_js.html

I'm just getting a blank page. The JS debugger tells me that the maps.js file is looking for an API key, which I have for Maps. However, I'm not seeing where exactly in the code I could pass in that API key. It's probably quite simple and I'm missing it, but I'm curious to see if I can get this working on a phone. 

I found this repo through this [tutorial](http://tonyredhead.com/google-tips/codegenerator), and it's quite lovely -- thank you for creating it! 

Thanks!

<img width="1044" alt="screen shot 2016-04-01 at 8 23 31 am" src="https://cloud.githubusercontent.com/assets/13929672/14196139/267de888-f7e3-11e5-921e-f31bfc2c5e97.png">

**Comment by filutkie** [comment]
Hi Rob! 
I've inspected your web-page and found that your body was 0px height. The code was identical to the Embed Tool output but except of `<!DOCTYPE html>` line. And seems that was the problem! (you can google something like "doctype html not working" as I did). After I removed doctype line the page has rendered correctly.

The most right **solution** for this issue is just to add this style into the `<head>` section (you can keep doctype as is):
```
<style>
  html, body {
    height: 100%;
    margin: 0;
  }
</style>
```
Hope that will work as needed. 

But please notice that Google's JS pano viewer is working not so smooth and awkward for now (both on desktop and mobile). I don't know what is the reason but I think Google engineers are aware of this problem.

**Comment by robweir** [comment]
Very odd that the doctype would cause that to happen. Thanks for getting back so quickly, though!

**Comment by robweir** [comment]
Also I should have mentioned, adding that style attribute worked perfectly. Thanks again!

**Comment by filutkie** [comment]
Thanks for letting me know, I'm glad it helped you!
